_BASE_: "../Base-ORCNN-FPN_D2SA.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (40000, 60000)
  MAX_ITER: 70000
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'orcnn_amodal_d2sa_res50_SGD_1x'
