_BASE_: "../Base-RCNN-FPN-KINS.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    VERSION: 3
    ATTENTION_MODE: "attention"
    GT_AMODAL_WEIGHT: 0.5
    GT_VISIBLE_WEIGHT: 0.5
    RECLS_NET:
      NAME: "ReclsConvFCHead"
      MODE: "adaptive"
      GT_WEIGHT: 0.1
      RESCORING: True
    RECON_NET:
      NAME: "General_Recon_Net"
      NORM: ""
      MEMO_AUG: False
      BOX_THS: 0.8
      MASK_THS: 0.95
      NUM_CONV: 2
      ALPHA: 2.0
      LOAD_CODEBOOK: True
      RESCORING: True
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_CtRef_VAR_SPRet_kins_res50_SGD_1x'