_BASE_: "../Base-ORCNN-FPN_KINS.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (40000, 44000)
  MAX_ITER: 48000
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'orcnn_amodal_kins_res50_SGD_1x'
