_BASE_: "../Base-RCNN-FPN-KINS.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    ATTENTION_MODE: "attention"
    VERSION: 1
    RECLS_NET:
      NAME: "ReclsConvFCHead"
      MODE: "adaptive"
      GT_WEIGHT: 0.1
      RESCORING: True
    RECON_NET:
      NAME: "General_Recon_Net"
      NORM: ""
      BOX_THS: 0.8
      MASK_THS: 0.95
      NUM_CONV: 2
      ALPHA: 3.0
      RESCORING: True
      LOAD_CODEBOOK: True
      MEMORY_REFINE: True
      MEMORY_REFINE_K: 16

TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_VAR_SPRef_SPRet_KINS_res50_SGD_1x'