_BASE_: "../Base-RCNN-FPN-KINS.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    VERSION: 3
    ATTENTION_MODE: "attention"
    GT_AMODAL_WEIGHT: 0.5
    GT_VISIBLE_WEIGHT: 0.5
    RECON_NET:
      NAME: "General_Recon_Net"
      NORM: ""
      BOX_THS: 0.8
      MASK_THS: 0.95
      NUM_CONV: 2
      ALPHA: 3.0
      RESCORING: True
      LOAD_CODEBOOK: True
      MEMORY_REFINE: True
      MEMORY_REFINE_K: 16

TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_CtRef_SPRef_SPRet_kins_res50_SGD_1x'