_BASE_: "../Base-RCNN-FPN-COCOA_cls.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    VERSION: 3
    ATTENTION_MODE: "attention"
    RECLS_NET:
      NAME: "ReclsConvFCHead"
      MODE: "adaptive"
      GT_WEIGHT: 0.1
      RESCORING: True

TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_CtRef_VAR_cocoa_cls_res50_SGD_1x'