_BASE_: "../Base-RCNN-FPN-D2SA.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  ROI_BOX_HEAD:
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
  ROI_MASK_HEAD:
    NORM: "GN"
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_amodal_d2sa_res101_3x_GN_memo'
