_BASE_: "../Base-RCNN-FPN-D2SA.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("d2sa_train_aug","d2sa_train")
  TEST: ("d2sa_val",)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (60000, 60000)
  MAX_ITER: 90000
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_amodal_d2sa_res101_1x_occl'