_BASE_: "../Base-RCNN-FPN-Amodal_Memo.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  ROI_BOX_HEAD:
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
  ROI_MASK_HEAD:
    NORM: "GN"
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00125
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_amodal_d2sa_res101_2x_GN_memo'
